# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@system/@root" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/6a04abfa-c46e-483d-88bf-e8db9821bc65";

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@system/@log" ];
      neededForBoot = true;
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@system/@tmp" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@local/@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/afa15e44-c5e7-4976-9c09-a48d68e8eba1";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1454-E77B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u3u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
